export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to CareMol – Care Close to You",
    selectLabel: "Please select your language",
    menuHeader: "We provide home sample collection within 5 km of Melattur 🏠\nHow can I help you?",
    options: {
      book: "Book Blood Test",
      packages: "View Packages",
      availability: "Check Availability",
      support: "Support"
    },
    askLocation: "Please share your location or enter your PIN code",
    greetName: "👋 Welcome back, {name}!",
    returningHeader: "How can I help you today?",
    selectPatient: "Who are you booking for?",
    someoneElse: "Someone else",
    changeLanguage: "Change Language",
    available: "Service available in your area ✅",
    unavailable: "Currently we serve only within 5 km of Melattur",
    askTest: "What test do you want to book?",
    packagesList: ["Basic Health Check", "Diabetes Profile", "Full Body Checkup"],
    patientName: "Enter patient name",
    patientAge: "Enter age",
    patientGender: "Select gender",
    genderOptions: ["Male", "Female", "Other"],
    patientPhone: "Enter contact number",
    patientAddress: "Enter full address with landmark",
    timeSlot: "Choose preferred time:",
    slots: ["08:00 AM – 10:00 AM", "10:00 AM – 12:00 PM", "02:00 PM – 04:00 PM", "04:00 PM – 06:00 PM"],
    fastingCheck: "This test requires fasting for 8–12 hours. Are you prepared?",
    confirmHeader: "Confirm booking?",
    paymentHeader: "Select payment method:",
    paymentOptions: ["UPI", "Cash on Collection"],
    success: "Booking Confirmed ✅",
    bookingId: "Booking ID",
    phlebMsg: "Phlebotomist will arrive at selected time",
    reportReady: "Your report is ready\nDownload: caremol.in/report/CM123",
    shareToWhatsApp: "Share to WhatsApp",
    endSession: "End Chat",
    sessionEnded: "Chat session ended. Type anything to start again.",
    mainMenu: "Main Menu",
    interestedInBooking: "Are you interested in booking a test?",
    confirmNamePrompt: "Is the patient's name **{name}**?",
    yesCorrect: "Yes, it's correct",
    noChange: "No, let me change",
    invalidNameError: "That doesn't look like a valid name. Please use only letters and avoid generic greetings.",
    confirmAddressPrompt: "Is this your full address?\n\n**{address}**",
    confirmPhonePrompt: "Is this the correct contact number?\n\n**{phone}**",
    cancelBooking: "Cancel Booking",
    doneSelecting: "✅ Done Selecting",
    selectedTestsPrefix: "Selected tests",
    selectAtLeastOneTest: "Please select at least one test to continue.",
    anyAdditionalTests: "Any additional tests needed?",
    packageIncludes: "Included tests: {details}",
    bookNow: "Book Now",
    backToPackages: "Back to Packages",
    selectPackageToView: "Select a package to view details:",
    backToMainMenu: "⬅️ Back to Main Menu",
    confirmCancelHeader: "Are you sure you want to cancel this booking?",
    yesCancel: "Yes, Cancel",
    continueBooking: "No, Continue Booking",
    patientDetailsEntry: "Please enter patient details:\n\n*Format:* Name, Age, Phone Number\n*Example:* John Doe, 32, 9876543210",
    patientBasicDetailsPrompt: "Please enter patient details:\n\nName:\nAge:\nPhone Number:",
    changeLocation: "📍 Change Location",
    enterAnotherPin: "🔢 Enter Another PIN Code",
    serviceUnavailable: "Currently service is not available in this area.",
    askNotes: "Any specific instructions or notes for the phlebotomist? (Optional - type 'None' or skip)",
    none: "None",
    genderMap: {
      "Male": "Male",
      "Female": "Female",
      "Other": "Other"
    }
  },
  ml: {
    welcome: "CareMol ലേക്ക് സ്വാഗതം – Care Close to You",
    selectLabel: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    menuHeader: "Melattur ചുറ്റുമുള്ള 5 km പരിധിയിൽ home sample collection ലഭ്യമാണ് 🏠\nനിങ്ങളെ എങ്ങനെ സഹായിക്കാം?",
    options: {
      book: "ടെസ്റ്റ് ബുക്ക് ചെയ്യുക",
      packages: "പാക്കേജുകൾ കാണുക",
      availability: "സർവീസ് ലഭ്യമാണോ പരിശോധിക്കുക",
      support: "സഹായം"
    },
    askLocation: "ലൊക്കേഷൻ അയക്കുക അല്ലെങ്കിൽ പിൻകോഡ് നൽകുക",
    greetName: "👋 വീണ്ടും സ്വാഗതം, {name}!",
    returningHeader: "ഇന്ന് നിങ്ങളെ എങ്ങനെ സഹായിക്കാം?",
    selectPatient: "ആർക്ക് വേണ്ടിയാണ് മെഡിക്കൽ ടെസ്റ്റ് ബുക്ക് ചെയ്യുന്നത്?",
    someoneElse: "മറ്റൊരാൾക്ക്",
    changeLanguage: "ഭാഷ മാറ്റുക",
    available: "നിങ്ങളുടെ പ്രദേശത്ത് സേവനം ലഭ്യമാണ് ✅",
    unavailable: "ഇപ്പോൾ Melattur ചുറ്റുമുള്ള 5 km പരിധിയിൽ മാത്രം സേവനം ലഭ്യമാണ്",
    askTest: "ഏത് ടെസ്റ്റ് ആണ് ബുക്ക് ചെയ്യേണ്ടത്?",
    packagesList: ["ബേസിക് ഹെൽത്ത് ചെക്ക്", "ഡയബറ്റീസ് പ്രൊഫൈൽ", "ഫുൾ ബോഡി ചെക്കപ്പ്"],
    patientName: "രോഗിയുടെ പേര് നൽകുക",
    patientAge: "പ്രായം നൽകുക",
    patientGender: "ലിംഗം തിരഞ്ഞെടുക്കുക",
    genderOptions: ["പുരുഷൻ", "സ്ത്രീ", "മറ്റ്"],
    patientPhone: "ഫോൺ നമ്പർ നൽകുക",
    patientAddress: "വിലാസം (ലാൻഡ് മാർക്ക് ഉൾപ്പെടെ) നൽകുക",
    timeSlot: "സമയം തിരഞ്ഞെടുക്കുക:",
    slots: ["08:00 AM – 10:00 AM", "10:00 AM – 12:00 PM", "02:00 PM – 04:00 PM", "04:00 PM – 06:00 PM"],
    fastingCheck: "ഈ ടെസ്റ്റിന് 8–12 മണിക്കൂർ ഉപവാസം ആവശ്യമാണ്. തയ്യാറാണോ?",
    confirmHeader: "ബുക്കിംഗ് സ്ഥിരീകരിക്കണോ?",
    paymentHeader: "പേയ്‌മെന്റ് രീതി തിരഞ്ഞെടുക്കുക:",
    paymentOptions: ["UPI", "Cash on Collection"],
    success: "ബുക്കിംഗ് സ്ഥിരീകരിച്ചു ✅",
    bookingId: "ബുക്കിംഗ് ഐഡി",
    phlebMsg: "നിശ്ചിത സമയത്ത് സ്റ്റാഫ് എത്തും",
    reportReady: "നിങ്ങളുടെ റിപ്പോർട്ട് തയ്യാറായി\nഡൗൺലോഡ് ചെയ്യുക: caremol.in/report/CM123",
    shareToWhatsApp: "വാട്സാപ്പിൽ അയക്കുക",
    endSession: "ചാറ്റ് അവസാനിപ്പിക്കുക",
    sessionEnded: "ചാറ്റ് അവസാനിച്ചു. വീണ്ടും തുടങ്ങാൻ സന്ദേശം അയക്കുക.",
    mainMenu: "പ്രധാന മെനു",
    interestedInBooking: "ടെസ്റ്റ് ബുക്ക് ചെയ്യാൻ നിങ്ങൾക്ക് താൽപ്പര്യമുണ്ടോ?",
    confirmNamePrompt: "രോഗിയുടെ പേര് **{name}** എന്നത് ശരിയാണോ?",
    yesCorrect: "അതെ, ശരിയാണ്",
    noChange: "അല്ല, മാറ്റണം",
    invalidNameError: "ദയവായി ശരിയായ പേര് നൽകുക. അക്ഷരങ്ങൾ മാത്രം ഉപയോഗിക്കുക.",
    confirmAddressPrompt: "ഇതാണ് നിങ്ങളുടെ പൂർണ്ണ വിലാസം എന്നത് ശരിയാണോ?\n\n**{address}**",
    confirmPhonePrompt: "ഈ ഫോൺ നമ്പർ ശരിയാണോ?\n\n**{phone}**",
    cancelBooking: "ബുക്കിംഗ് റദ്ദാക്കുക",
    doneSelecting: "✅ തിരഞ്ഞെടുത്തു കഴിഞ്ഞു",
    selectedTestsPrefix: "തിരഞ്ഞെടുത്ത ടെസ്റ്റുകൾ",
    selectAtLeastOneTest: "തുടരുന്നതിന് ദയവായി കുറഞ്ഞത് ഒരു ടെസ്റ്റ് എങ്കിലും തിരഞ്ഞെടുക്കുക.",
    anyAdditionalTests: "കൂടുതൽ ടെസ്റ്റുകൾ വേണോ?",
    packageIncludes: "ഉൾപ്പെടുത്തിയിരിക്കുന്ന ടെസ്റ്റുകൾ: {details}",
    bookNow: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
    backToPackages: "മറ്റ് പാക്കേജുകൾ കാണുക",
    selectPackageToView: "വിശദാംശങ്ങൾ കാണാൻ ഒരു പാക്കേജ് തിരഞ്ഞെടുക്കുക:",
    backToMainMenu: "⬅️ പ്രധാന മെനുവിലേക്ക്",
    confirmCancelHeader: "ഈ ബുക്കിംഗ് റദ്ദാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
    yesCancel: "അതെ, റദ്ദാക്കുക",
    continueBooking: "അല്ല, ബുക്കിംഗ് തുടരുക",
    patientDetailsEntry: "രോഗിയുടെ വിവരങ്ങൾ താഴെ പറയുന്ന രീതിയിൽ നൽകുക:\n\n*Format:* പേര്, പ്രായം, ഫോൺ നമ്പർ\n*Example:* സുരേഷ്, 35, 9876543210",
    patientBasicDetailsPrompt: "രോഗിയുടെ വിവരങ്ങൾ താഴെ പറയുന്ന രീതിയിൽ നൽകുക:\n\nപേര്:\nപ്രായം:\nഫോൺ നമ്പർ:",
    changeLocation: "📍 ലൊക്കേഷൻ മാറ്റുക",
    enterAnotherPin: "🔢 മറ്റൊരു പിൻകോഡ് നൽകുക",
    serviceUnavailable: "നിലവിൽ ഈ പ്രദേശത്ത് സേവനം ലഭ്യമല്ല.",
    askNotes: "സ്റ്റാഫിന് പ്രത്യേക നിർദ്ദേശങ്ങൾ വല്ലതും ഉണ്ടോ? (നിർബന്ധമില്ല - 'ഇല്ല' എന്ന് ടൈപ്പ് ചെയ്യുകയോ ഒഴിവാക്കുകയോ ചെയ്യാം)",
    none: "ഇല്ല",
    genderMap: {
      "പുരുഷൻ": "Male",
      "സ്ത്രീ": "Female",
      "മറ്റ്": "Other"
    }
  }
};

export const TEST_PRICES: Record<string, number> = {
  "Basic Health Check": 499,
  "Diabetes Profile": 799,
  "Full Body Checkup": 1499,
  "ബേസിക് ഹെൽത്ത് ചെക്ക്": 499,
  "ഡയബറ്റീസ് പ്രൊഫൈൽ": 799,
  "ഫുൾ ബോഡി ചെക്കപ്പ്": 1499,
};

export const PACKAGE_DESCRIPTIONS: Record<string, string> = {
  "Basic Health Check": "CBC, Glucose Fasting, Cholesterol, Urine Routine",
  "Diabetes Profile": "HbA1c, Glucose Fasting & PP, Lipid Profile",
  "Full Body Checkup": "CBC, Liver Function, Kidney Function, Thyroid, Vitamin D, Lipid Profile, Glucose",
  "ബേസിക് ഹെൽത്ത് ചെക്ക്": "സിബിസി, ഗ്ലൂക്കോസ് ഫാസ്റ്റിംഗ്, കൊളസ്ട്രോൾ, യൂറിൻ റുട്ടീൻ",
  "ഡയബറ്റീസ് പ്രൊഫൈൽ": "HbA1c, ഗ്ലൂക്കോസ് ഫാസ്റ്റിംഗ് & പിപി, ലിപിഡ് പ്രൊഫൈൽ",
  "ഫുൾ ബോഡി ചെക്കപ്പ്": "സിബിസി, ലിവർ ഫംഗ്ഷൻ, കിഡ്നി ഫംഗ്ഷൻ, തൈറോയ്ഡ്, വിറ്റാമിൻ ഡി, ലിപിഡ് പ്രൊഫൈൽ, ഗ്ലൂക്കോസ്",
};
